# Creating Numpy Arrays
1. Using np.array()//1-D and 2-D
2. Using np.zeros/ones/empty/random()
3. Using np.arange()
4. Using np.linspace()
5. Using Copy()
6. Using Identity()

In [2]:
import numpy as np


1. Using np.array()//1-D and 2-D


In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1) # numpy libray ka ndarray nam ka object hai

numpy.ndarray

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.zeros((2,3)) #rows = 2, column = 3 
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr6 = np.arange(10) #0 se 9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr6 = np.arange(16) #0 se 9
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [20]:
arr7 = np.linspace(10,20,10) #distance btw two point is same
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# Properties & Attributes
1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [22]:
arr1  

array([1, 2, 3, 4, 5])

In [24]:
arr1.shape

(5,)

In [25]:
print(arr2)
arr2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [37]:
arr9 = np.array([[[1,2],[2,3]],[[3,4],[5,6]]])
print(arr9)
print(arr9.shape)
arr9.ndim # ndim is a attribute not a function that why we don't use () here

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]]
(2, 2, 2)


3

In [38]:
arr9.shape

(2, 2, 2)

In [39]:
arr9.itemsize

4

In [40]:
arr8.itemsize    

8

In [41]:
arr8.dtype

dtype('float64')

In [42]:
arr9.dtype

dtype('int32')

In [43]:
arr9.astype('float')

array([[[1., 2.],
        [2., 3.]],

       [[3., 4.],
        [5., 6.]]])

# Numpy Array Vs Python Lists

# Lists Vs Arrays array>>lists
1. Faster
2. Convenient
3. Less Memory

In [44]:
lista = range(100)
lista

range(0, 100)

In [45]:
arr11 = np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
import sys 

In [48]:
print(sys.getsizeof(87)*len(lista)) #2800 bytes

2800


In [49]:
print(arr11.itemsize*arr11.size) #size se no of item nikalta hai

400


In [50]:
import time

In [54]:
x = range(100000)
y = range(100000, 200000)


start_time = time.time()

c = [(x + y) for x,y in zip(x,y) ]

print(time.time() - start_time)

0.006512880325317383


In [56]:
a = np.arange(100000)
b = np.arange(100000, 200000)

start_time = time.time()
c = a + b

print(time.time()- start_time)

0.002080202102661133


#### Adding 2 zeroes 

In [57]:
x = range(10000000)
y = range(10000000, 20000000)


start_time = time.time()

c = [(x + y) for x,y in zip(x,y) ]

print(time.time() - start_time)

0.6025404930114746


In [58]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a + b

print(time.time()- start_time)

0.080596923828125


## Indexing, Slicing and Iteration

In [59]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
arr1

array([1, 2, 3, 4, 5])

In [65]:
arr1[2:3]

array([3])

In [66]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
arr12[2]

array([ 8,  9, 10, 11])

In [ ]:
arr12[:,2: 4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [73]:
arr12[2:3,1: 3]

array([[ 9, 10]])

In [74]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [76]:
for i in np.nditer(arr12):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
